version: '3.8'
services:
  web:
    build: .
    image: ibkr-rest-api
    container_name: ibkr
    environment:
      IBKR_ACCOUNT_ID: "U1234567"
    ports:
      - "5055:5055"
      - "5056:5056"
    volumes:
      - ./webapp:/app/webapp
